runmode: debug                 # 开发模式, debug, release, test
runenv: local
loadLocation: Asia/Shanghai
http:  # http配置
  host:                        # http监听地址
  port: 8080                   # http监听端口
  shutdown_timeout: 60         # http优雅关闭等待超时时长(单位秒)
  name: apiserver              # API Server的名字
  url: http://localhost:8080   # pingServer函数请求的API服务器的ip:port
  max_ping_count: 2            # pingServer函数try的次数
jwt_secret: Rtg8BPsKNE4f2mB4mgvzKONGPZZQSaJWNLijxR425qRgq0iBb5
log:
  level: 5  # 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
  format: text # 日志格式（支持输出格式：text/json）
  output: stdout  # 日志输出(支持：stdout/stderr/file)
  output_file: log/ginadmin.log  # 指定日志输出的文件路径
  enable_hook: false  # 是否启用日志钩子
  hook: gorm  # 日志钩子(支持：gorm)
  hook_max_thread: 1  # 写入钩子的最大工作线程数量
  hook_max_buffer: 7  # 写入钩子的最大缓冲区数量
log_gorm_hook: # 日志gorm钩子配置
  db_type: mysql  # 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
  max_lifetime: 7200  # 设置连接可以重用的最长时间(单位：秒)
  max_open_conns: 1  # 设置数据库的最大打开连接数
  max_idle_conns: 1  # 设置空闲连接池中的最大连接数
  table: "logger"  # 数据库表名
db:
  name: wfgsmall
  addr: 127.0.0.1:3306
  username: root
  password: root
  debug: true
redis:
  addr: 127.0.0.1:6399
  password: 123456
  db: 1
  dbapi: 4
