// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"app/internal/biz"
	"app/internal/config"
	"app/internal/data"
	"app/internal/service"
)

// Injectors from wire.go:

func InitializePostService(cfg *config.Config) (*service.PostService, error) {
	db, err := data.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	postData := data.NewPostData(db)
	postBiz := biz.NewPostBiz(postData)
	postService := service.NewPostService(postBiz)
	return postService, nil
}
