// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"app/internal/biz"
	"app/internal/data"
	"app/internal/service"
)

// Injectors from wire.go:

func InitializePostService() *service.PostService {
	postData := data.NewPostData()
	postBiz := biz.NewPostBiz(postData)
	postService := service.NewPostService(postBiz)
	return postService
}
